package ch.hslu.oop.SW08.Element;

public enum ElementClassification {
    ALKALI_METALS, ALKALINE_EARTH_METALS, TRANSITION_METALS, OTHER_METALS, METALLOIDS, NON_METALS, HALOGENS, NOBLE_GASES, RARE_EARTH_ELEMENTS
}
